Models/Employee.cs
namespace DataBaseCRUD.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SureName { get; set; }
        public string Address { get; set; }
        private string _fullName;
        public string FullName
        {
            get { return Name+" "+SureName; }
            set { _fullName = value; }
        }
        public string Photo { get; set; }

    }
}

Models/ErrorViewModel.cs
using System;

namespace DataBaseCRUD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EmployeeManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DataBaseCRUD.Models;
using DataBaseCRUD.Data;

namespace DataBaseCRUD.Controllers
{
    public class EmployeeManagementController : Controller
    {
        private readonly AppDbContext _context;
        //private readonly FakeData _context;

        //Dependency Injection. Bağımlı Enjeksiyon
        public EmployeeManagementController(AppDbContext context) //Constructure
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Employees);
        }

        //method-----> Action To Open The View.
        public IActionResult Create()
        {
            return View();//form ----->>>>>>>model binding>>>>>>>>----------> Personel
            // will get the object from the form in our view 
            //and pass it to the other create function to be saved in the database.
        }
        [HttpPost] // Post\Save Action To Save The Writen Informations in The View To The DB.
        public IActionResult Create(Employee employee)
        {
             //this function will save the passed object from the previous function into the database. 
            _context.Employees.Add(employee);
            return RedirectToAction("Index");
        }

        //method-----> Action For Showing Details.
        public IActionResult Details(int id)
        {
            var employee = _context.Employees.Where(x => x.Id == id).SingleOrDefault();
            return View(employee);
        }
        // Action For Deleting an Employee By His Id.
        public IActionResult Delete(int id)
        {
            //We have to add some conformation to this action.
            var employee = _context.Employees.SingleOrDefault(x => x.Id == id);
            //var employee1 = _context.Employees;
            _context.Employees.Remove(employee);
            return RedirectToAction("Index");
        }

        //method-----> Action
        public IActionResult Edit(int id)
        {
            // id(int) ------- LINQ   -------> Employee(reference)
            var employee = _context.Employees.SingleOrDefault(x => x.Id == id);
            return View(employee); // form <----model binding----- Employee
        }

        //method-----> Post\Save Action
        [HttpPost]
        public async Task<IActionResult> Edit(Employee _selectedEmployee)
        {
            var _toupdateEmployee = _context.Employees.Where(x => x.Id == _selectedEmployee.Id).SingleOrDefault();
            await TryUpdateModelAsync(_toupdateEmployee);
            //_context.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DataBaseCRUD.Models;

namespace DataBaseCRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/EmployeeManagement/Create.cshtml
@model Employee

<div class="jumbotron mt-5">
    <h1 class="text-primary">Create New Employee</h1>
    <hr>
    <div class="row">
        <div class="col-8">
            <form asp-action="Create">
                <div class="form-group was-validated">
                    <label for="id">Id</label>
                    <input asp-for="Id" type="number" class="form-control is-invalid" id="id" required
                        aria-describedby="desciption">
                    <small id="desciption" class="form-text text-muted">Enter an Unique Id.</small>
                </div>
                <div class="form-group was-validated">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" class="form-control is-invalid" id="name" asp-for="Name" required>
                </div>
                <div class="form-group was-validated">
                    <label for="sureName">SureName</label>
                    <input asp-for="SureName" type="text" class="form-control is-invalid" id="sureName" required>
                </div>
                <div class="form-group">
                    <label for="address" class="form-label">Address</label>
                    <input asp-for="Address" type="text" class="form-control" id="address"
                        placeholder="Apartment, studio, or floor">
                </div>
                <div class="card" style="padding:2rem;">
                    <div class="row">
                        <div class="form-group col">
                            <label for="photo">Photo</label>
                            <input asp-for="Photo" type="text" class="form-control" id="photo"
                                aria-describedby="resimYardim" placeholder="ahmet.jpg">
                            <small id="resimYardim" class="form-text text-muted">Enter The Image's Path.</small>
                        </div>
                        <div class="form-group col">
                            <label for="imgInp">Or Upload Image</label>
                            <div class="input-group">
                                <span class="input-group-btn">
                                    <span class="btn btn-default btn-file">
                                        <input type="file" asp-for="Photo" id="imgInp">
                                    </span>
                                </span>
                            </div>
                            <img id='img-upload' class="img-thumbnail" />
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
            @* <form asp-action="Create">

                <div class="form-group">
                <label for="id">Id</label>
                <input asp-for="Id" type="number" class="form-control" id="id" aria-describedby="sicilNoYardim">
                <small id="sicilNoYardim" class="form-text text-muted">Benzersiz bir sicil numarası
                girilmelidir</small>
                </div>

                <div class="form-group">
                <label for="name">Name</label>
                <input asp-for="Name" type="text" class="form-control" id="name">
                </div>

                <div class="form-group">
                <label for="sureName">SureName</label>
                <input asp-for="SureName" type="text" class="form-control" id="sureName">
                </div>

                <div class="form-group">
                <label for="photo">Photo</label>
                <input asp-for="Photo" type="text" class="form-control" id="photo" aria-describedby="resimYardim"
                placeholder="ahmet.jpg">
                <small id="resimYardim" class="form-text text-muted">Resmin yolu girilmedir</small>
                </div>

                <button type="submit" class="btn btn-primary">Create</button>
                </form> *@
        </div>
    </div>
</div>

Views/EmployeeManagement/Details.cshtml
@model Employee
<div class="jumbotron mt-5">
<h2 class="text-danger">@Model.FullName</h2>
<h5 class="text-primary">(@Model.Id)</h5>
<hr>

<img src="/EmployeesPhotos/@Model.Photo" style="width: 250px;" alt="@Model.Name">
</div>
<a asp-action="Index" class="btn btn-secondary mt-3">Back</a>

Views/EmployeeManagement/Edit.cshtml
@model Employee

<div class="jumbotron mt-5">
    <h1 class="text-primary">Edit Employee</h1>
    <hr>
    <div class="row">
        <div class="col-8">
            <form asp-action="Edit">
                <div class="form-group was-validated">
                    <label for="id">Id</label>
                    <input asp-for="Id" type="number" class="form-control" id="id" readonly
                        aria-describedby="desciption">
                    <small id="desciption" class="form-text text-muted">Enter an Unique Id.</small>
                </div>
                <div class="form-group was-validated">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" class="form-control is-invalid" id="name" asp-for="Name" required>
                </div>
                <div class="form-group was-validated">
                    <label for="sureName">SureName</label>
                    <input asp-for="SureName" type="text" class="form-control is-invalid" id="sureName" required>
                </div>
                <div class="form-group">
                    <label for="address" class="form-label">Address</label>
                    <input asp-for="Address" type="text" class="form-control" id="address"
                        placeholder="Apartment, studio, or floor">
                </div>
                <div class="card" style="padding:2rem;">
                    <div class="row">
                        <div class="form-group col">
                            <label for="photo">Photo</label>
                            <input asp-for="Photo" type="text" class="form-control" id="photo"
                                aria-describedby="resimYardim" placeholder="ahmet.jpg">
                            <small id="resimYardim" class="form-text text-muted">Enter The Image's Path.</small>
                        </div>
                        <div class="form-group col">
                            <label for="imgInp">Or Upload Image</label>
                            <div class="input-group">
                                <span class="input-group-btn">
                                    <span class="btn btn-default btn-file">
                                        <input type="file" asp-for="Photo" id="imgInp">
                                    </span>
                                </span>
                            </div>
                            <img id='img-upload' class="img-thumbnail" />
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
                <button asp-action="Index" class="btn btn-secondary">Cancel</button>
            </form>

        </div>
    </div>
</div>

Views/EmployeeManagement/Index.cshtml
@model IEnumerable<Employee>
<div class="jumbotron mt-5">
    <h2 class="text-danger">Employees List</h2>

    <a asp-action="Create" class="btn btn-outline-primary mt-3">New Employee</a>
    <input type="text" class="form-control mt-3" placeholder="Enter Name" id="name">
    <table class="table table-hover mt-3">
        <thead>
            <th>Id</th>
            <th>Name</th>
            <th>Address</th>
            <th>Option</th>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.FullName</td>
                <td>@item.Address</td>
                <td>
                    @*To pass a parametar to the view we used asp-rout-id*@
                    <a class="btn btn-outline-primary" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    @*To pass a parametar to the view we used asp-rout-id*@
                    <a class="btn btn-outline-secondary" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    <!-- Button trigger modal -->
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal@(item.Id)">
                        Delete
                    </button>

                    <!-- Modal -->
                <div class="modal fade" id="modal@(item.Id)" tabindex="-1" role="dialog"
                    aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Deleting Employee</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <img src="/EmployeesPhotos/@item.Photo" style="width: 50px;"><span class="text-danger">@item.FullName</span>
                                    <hr style="width: 80%;">
                                    This Employees Informations Will be Deleted. Are You Sure You Want To Do That?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    @*The button tag wont work here as delete action. That's why we change it to a tag*@
                                    <a class="btn btn-danger" asp-action="Delete"
                                    asp-route-id="@item.Id">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>



                </td>
            </tr>
        }
    </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FackDataBaseCRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FackDataBaseCRUD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-area="" asp-controller="EmployeeManagement" asp-action="Index">Employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FackDataBaseCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>